### ISSUE TITLE
Describe list of features for MVP

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#1]
# Dexter Product Features
#### Miscellaneous
- [x] Connect / Disconnect wallet https://github.com/DeXter-on-Radix/website/issues/12
#### Selecting asset pairs
- [x] Show scrollable list of supported alphadex pairs
- [x] Clicking on a pair updates the relevant UI components (pair-overview-bar, chart, order-book, recent trades)
#### Order Book
- [x] Simple order book, list of 8 buy and 8 sell orders
#### Create order
- [x] Create market order (handle prevent immediate execution)
- [x] Create limit order
- [x] Select from predefined percentages or input custom percentage.
- [x] Instantaneous Fee calculation when trade size is entered, before execution
#### Order details
- [x] Current orders list
- [x] Orders history list
- [x] Trade history list
- [x] Cancel unfilled limit order

## Launch 
- [x] Instantaneous Fee calculation when trade size is entered, before execution

## Backlog
- [x] TP/SL orders: create/cancel/cancel untriggered
#### Order Book
- [x] Change order book depth (aka aggregation)
- [ ] Scrollable buy/sell lists?
- [x] Coloured background bars
#### Selecting asset pairs
- [ ] Search asset pair
- [ ] Add/remove pairs from a favourite pairs list
- [ ] Ability to switch between top X pairs list or favourites list of pairs
#### Others
- [ ] Recent trades list (for the selected pair)
- [ ] List of recent user's transactions
- [ ] ability to select fiat currency that values should be displayed in
- [ ] View wallet balances directly in dexter’s UI (aka portfolio view)
- [ ] Export trade history to .csv
- [ ] Add alternative layouts for order book (only buy or sell orders)
- [ ] Add new pair on AlphaDEX

# Dexter Landing Page Features
- [ ] Overall Exchange Stats (number of pairs, 24h value traded, etc)
- [ ] List op top X pairs by volume traded with some details of each pair (e.g. pair name, last price, 24h value traded etc)

---

We had a vote about features roughly described here https://strawpoll.com/wAg3A73qly8/results

In this issue let's define the exact list that will be in the MVP and maybe some description.

Wireframes are here: https://www.figma.com/file/P7pfzKwJ4G6ClapXfl61D3/Dexter-Wireframes?type=design&node-id=30%3A5591&mode=design&t=TgB26jrgh0cmzhpo-1

**Comment by EvgeniiaVak** [comment]
After having the initial design ready, it would be super useful if somebody could fill in the exact values of colors in a structure like here https://daisyui.com/theme-generator/ (If there are not enough fields, you can create a new list and just share it as text here. Having string values for the colors for both light and dark modes will greatly simplify development:

```TS
theme: {
 "primary": "#ce4057",
 "secondary": "#0660d6",
 "accent": "#77e584",
 "neutral": "#2a363c",
 "base-100": "#3b4f59",
 "info": "#4e94e4",
 "success": "#50e2c3",
 "warning": "#f6c709",
 "error": "#f91f06",
},
```

**Comment by steferr** [comment]
I'll take care of it

**Comment by steferr** [comment]
## Features (first draft)
#### Miscellaneous
- [ ] Connect / Disconnect wallet
- [ ] View wallet balances directly in dexter’s UI
- [ ] Recent trades list
#### Selecting asset pairs
- [ ] Search asset pair
- [ ] Add/remove pairs from a favourite pairs list
- [ ] Clicking on a pair updates the relevant UI components (pair-overview-bar, chart, order-book, recent trades)
#### Order Book
- [ ] View order book (just one layout for MVP), show spread
- [ ] Change order book depth
#### Create order
- [ ] Create market order (handle prevent immediate execution)
- [ ] Create limit order
- [ ] Create TP/SL order
- [ ] Cancel TP/SL order
- [ ] Instantaneous Fee calculation when trade size is entered, before execution
#### Order details
- [ ] List of current orders
- [ ] List of orders history
- [ ] List of trade history
- [ ] Trade history (+ export to CSV)
- [ ] Cancel untriggered TP/SL order
- [ ] Cancel unfilled limit order

**Comment by EvgeniiaVak** [comment]
@steferr @Kafkafrate
currently, the dev version looks like this (we applied no styles what so ever and the content is mock):
<img width="1470" alt="Screenshot 2023-07-06 at 12 43 35" src="https://github.com/DeXter-on-Radix/website/assets/27793901/68fe5a8f-4150-4496-a535-6d0fd1b180b2">

I'm sharing it here just to raise 2 points related to the design:
1. the connect button is very hard to (I did not find yet how) style, it's injected into the dom by the radix library and is not very flexible atm, maybe we'll need our site design to play nicely with this blue color
2. maybe? we'll need some social links at the bottom (not youtube of course, it's just an example)

**Comment by Kafkafrate** [comment]
I think a good way to play around that Connect button to integrate nicely with our color theme, is to add it into a Dropdown menu and add there any other profile details of the user. 
Like that we can keep whatever design we want on the page, and just when you mouse over or click, the dropdown will reveal the actual Connect button and whatever user related settings we have there.

**Comment by EvgeniiaVak** [comment]
I like the dropdown idea, the only (maybe) problem for UX - it will require more clicks to do stuff

**Comment by Kafkafrate** [comment]
If the dropdown reacts to mouse over it's basically still one click :)
The thing is that I've seen after you log in, the radix UI of the button might have a dropdown of it's own. 
Not sure the current version if it has it but in the wallet mockups I've seen a dropdown. So that might be tricky to have a dropdown, in a dropdown.

**Comment by EvgeniiaVak** [comment]
yeah, it has a dropdown

**Comment by EvgeniiaVak** [comment]
I can style it actually...  but it'll be not beautiful code-wise - will be very dependent on what the lib has internally and might change in future versions.

the radix dropdown:
<img width="501" alt="Screenshot 2023-07-06 at 13 26 29" src="https://github.com/DeXter-on-Radix/website/assets/27793901/4f74076d-0cb8-4ff8-8625-93699fa3898c">

**Comment by EvgeniiaVak** [comment]
The MVP features are done, will create new issues for the ones listed in backlog during the upcoming call.
