### ISSUE TITLE
Deploy test version

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#36]
This issue is not about the real user-facing deployment (that is blocked by #8 ). This is about deploying a version of the website that our community can interact with during the development. This website should be connecting to the test network.

### pre-requisites

- [x] #27
- [x] #20 

### TODO
- [x] set up CI to build release files - kinda done, but not really needed for deploying the test version #87 
- [ ] ~~hide testnet version from search engines~~ - don't need to do much, because we "use client" in the root currently 😆 it pretty much throws SEO out of the window already 
- [ ] ~~(maybe) deploy to vercel~~ (paid-only for organizations)
- [x] deploy to IPFS 
- [ ] deploy to GitHub

---

Things to consider:
- Maybe we'll need a separate `development` branch, where we push all our usual pull requests, and it is automatically deployed to the test, but maybe having `main` branch directly is ok.
- We will probably need some kind of environment variables for separating testing deployment and real deployment in the future

**Comment by fliebenberg** [comment]
For now it is probably easier to just have a main branch, since everything is still "development". We can look at creating a development branch when we get close to launching the app on the mainnet. That way all PRs go into development and we do pulls into main on either a set timeframe or on feature deployments. I dont have any experience working on repos of this nature. I have mostly worked on my own, which makes things much simpler. So I am keen to hear how you think we should deal with different branches.

**Comment by EvgeniiaVak** [comment]
I agree, for now only `main` branch is good enough.

**Comment by fliebenberg** [comment]
Are you happy for me to close this issue for now? We can raise this again closer to deployment? I think we should have a bigger discussion about the shape of the repo once we get closer to deployment. For now we just work in feature-development branches and the main branch.

**Comment by fliebenberg** [comment]
One suggestion is that we start using a consistent naming convention for branches. When it is a feature we add "feature:" to the front of the branch name and if it is a fix, we add: "fix: " to the front of the branch name. It just makes it a bit clearer when looking through the branches. Happy for other suggestions to achieve the same thing.

**Comment by EvgeniiaVak** [comment]
@fliebenberg I wouldn't want to close this issue, the opposite I would like to deploy asap (I'm thinking right after we are done with #6 ) and share only with testers. The idea is to deploy the very basic functionality early so that people would be able to test and probably find bugs. Note this is not about MVP-user-ready deployment (that should be done after #8 discussion), this one is about deployment of our current state of the project, always fresh, might be broken or not pretty, but something for our non-dev community play with and leave feedback. 
We might want to think about how to hide it from search engines though 😆 
And in general I vote for not closing unfinished issues so that we don't forget about them. Better to create a separate Backlog column if we want to separate the some-day-maybe and todo.

**Comment by EvgeniiaVak** [comment]
Ok, deploying to Vercel is not free when deploying from a GitHub org:

![Screenshot 2023-08-28 at 11 09 57](https://github.com/DeXter-on-Radix/website/assets/27793901/a1dcf53c-8638-4251-b18d-a530f535fba1)

https://vercel.com/pricing
![Screenshot 2023-08-28 at 11 10 42](https://github.com/DeXter-on-Radix/website/assets/27793901/d6243c26-5252-4eeb-be2f-4ba3bb5f7262)

Will try deploying to GitHub.

**Comment by EvgeniiaVak** [comment]
@fliebenberg I was playing out with the deployment: https://evgeniiavak.github.io/dexter-website/ (it's from my fork, not from  `DeXter-on-Radix` org) and chrome gives the following errors when trying to connect to AlphaDEX:

<img width="1470" alt="Screenshot 2023-08-28 at 21 49 00" src="https://github.com/DeXter-on-Radix/website/assets/27793901/e886534d-b948-40ad-aa85-95b0274930b3">


Looks like a change is needed in the SDK? Maybe just replacing `ws://ws.alphadex.net/` to `wss://ws.alphadex.net/` would work?

**Comment by EvgeniiaVak** [comment]
@fliebenberg new sdk version:
```
"alphadex-sdk-js": "^0.8.1",
```
did not really help, new errors now (and they are present even locally):

![Screenshot 2023-08-29 at 16 33 59](https://github.com/DeXter-on-Radix/website/assets/27793901/ce9abb21-67e8-4000-addd-b9708378b377)

**Comment by fliebenberg** [comment]
@EvgeniiaVak can you just check again please. I think this error might have been related to the Gateway that was down. I have other users connecting without a problem and I can also connect, so we might need to bug-hunt a bit if you are still having this issue.

**Comment by EvgeniiaVak** [comment]
@fliebenberg nope, still not working, see this commit - https://github.com/DeXter-on-Radix/website/commit/52dccc86a9a80f69560d0ac6ae8a087b71676108
the only thing I changed is update the SDK, and it stops working (and before the update it works all right via http (locally))

**Comment by fliebenberg** [comment]
Hi. I am not sure why the wss is not working on the server, but will investigate. In the meantime, I have rolled back the change so that the latest version now again just uses ws://. You can just update to latest to revert back to ws://.

**Comment by EvgeniiaVak** [comment]
Moving this issue to post-MVP, because @Radstakes ( 🙏 ) deployed a version to IPFS and testing is now unblocked 💃 

When resuming this issue: can continue on branch: https://github.com/DeXter-on-Radix/website/tree/github-deploy-workflow the deployment itself works (example of a fork deployed with a similar job https://evgeniiavak.github.io/dexter-website/ ), but the page does not work correctly - adex sdk needs to be updated to support https (for non-ipfs-browsers).

**Comment by EvgeniiaVak** [comment]
We have https://test.dexteronradix.com/ on netlify, if github deployment is ever needed, the workflow can be found on [`github-deploy-workflow` branch](https://github.com/DeXter-on-Radix/website/tree/github-deploy-workflow).
