### ISSUE TITLE
Create "roadmap" page

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#562]
# Problem

Projects usually show a roadmap for new community members to quickly understand project progress and upcoming features. We've encountered several instances where people joined our Telegram group asking for this information.

# Solution

Create a roadmap/milestones page. The following steps are required:
- [ ] Collaborate with @maurojose on the design (e.g., should we use table, roadmap, or cards), and await Figma mockups.
- [ ] For each milestome, what data/info do we show? I suggest: 1) Title, 2) short description, 3) whos working on it, 4) status (in progress, not started, completed)
- [ ] I suggest storing the content in a Google Sheet, with data fetched similarly to how we store/load our KPIs.
- [ ] Gather a list of milestons from contributors (you can ask on TG or discord). Heres a good starting point: https://ductus.notion.site/DeXter-Developments-and-Milestones-83ae1e39fc574ace928efbb149c6a253

**Comment by yuliaSharabi** [comment]
@dcts I gave some feedback inside the document. FYI

**Comment by yuliaSharabi** [comment]
milestones=epics/roadmap features? @dcts
