### ISSUE TITLE
Tracking Slider Bugs

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#610]
Reported bug for slider:
- [ ] percentage slider if put to 100% sometimes shows "insufficient funds". Most likely a roinding error. Reported by Punk.
- [ ] on mobile, the slider, when touched and sliding, does not show the tooltip. You can reproduce by using mobile view in devtools
- [ ] on mobile, the slider input is buggy, because the getQuote API is being called on every onChange event of the slider. This should be debounced, such that the getQuote will only be called when the slider was not touched for 1s or similar timeframe.

**Comment by dcts** [comment]
https://t.me/dexter_discussion/22583

![IMG_20241128_125031](https://github.com/user-attachments/assets/fbd58638-a706-467c-a87f-ab7b25669cb0)
