### ISSUE TITLE
Order button updates

### ISSUE THREAD

**Issue by SmashingBumpkin** [DeXter-on-Radix/website#72]
I'm just opening this issue to consolidate all the feature adjustments needed for the order button. This consolidates previous issues/code todos.

New features:

- [x] Check user has funds to cover position size, show alert message if not (https://github.com/DeXter-on-Radix/website/issues/50)
- [ ] Check user is not using 100% of available xrd (https://github.com/DeXter-on-Radix/website/issues/50)

Feature adjustments/improvements:
- [x] Change price on a limit order is 5% below or above best buy/sell alert to be less intrusive (eg toast) (https://github.com/DeXter-on-Radix/website/issues/50)
- [x] Change slippage greater than 5% alert to be less intrusive (eg a toast) (https://github.com/DeXter-on-Radix/website/issues/50)
- [x] Adjust % button behaviour to put in the requested amount even if there is not liquidity
- [ ] Improve wording and information given in trade "description"
- [x] Quickly typing in a percentage position size on the "Buy" side sends a call to fetch balances too quickly. Might need debouncing

Other updates:
- [x] Automatic updating of balances (will be addressed in this issue: https://github.com/DeXter-on-Radix/website/pull/68)
- [x] Getting best buy/best sell prices (should eventually be addressed by this issue: https://github.com/DeXter-on-Radix/website/pull/68)
- [x] Implement proper design/styling

**Comment by EvgeniiaVak** [comment]
fixed by #117
